# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        db_provider:
            entity:
                class: AppBundle:User
                # if using multiple entity managers, manager_name: customer

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            #pattern: ^/
            #http_basic: ~
            #provider: db_provider
            logout_on_user_change: true

            form_login:
                login_path: /login
                check_path: /login
                provider: db_provider
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: /logout
                target: /

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    
    access_control:
        - { path: ^/(login|register), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # require ROLE_USER for /*
        - { path: ^/, roles: ROLE_USER }
